import { DateTime } from "luxon";

export type TimezoneOption = {
  value: string;
  label: string;
};

const toLabel = (timezone: string) => timezone.replace(/_/g, " ");

const getTimezoneOffsetMinutes = (timezone: string) => {
  const dateTime = DateTime.now().setZone(timezone);

  if (!dateTime.isValid) {
    return 0;
  }

  return dateTime.offset;
};

const ALL_TIMEZONE_OPTIONS: TimezoneOption[] = [
  { value: "UTC", label: toLabel("UTC") },
  { value: "Africa/Abidjan", label: toLabel("Africa/Abidjan") },
  { value: "Africa/Accra", label: toLabel("Africa/Accra") },
  { value: "Africa/Addis_Ababa", label: toLabel("Africa/Addis_Ababa") },
  { value: "Africa/Algiers", label: toLabel("Africa/Algiers") },
  { value: "Africa/Asmera", label: toLabel("Africa/Asmera") },
  { value: "Africa/Bamako", label: toLabel("Africa/Bamako") },
  { value: "Africa/Bangui", label: toLabel("Africa/Bangui") },
  { value: "Africa/Banjul", label: toLabel("Africa/Banjul") },
  { value: "Africa/Bissau", label: toLabel("Africa/Bissau") },
  { value: "Africa/Blantyre", label: toLabel("Africa/Blantyre") },
  { value: "Africa/Brazzaville", label: toLabel("Africa/Brazzaville") },
  { value: "Africa/Bujumbura", label: toLabel("Africa/Bujumbura") },
  { value: "Africa/Cairo", label: toLabel("Africa/Cairo") },
  { value: "Africa/Casablanca", label: toLabel("Africa/Casablanca") },
  { value: "Africa/Ceuta", label: toLabel("Africa/Ceuta") },
  { value: "Africa/Conakry", label: toLabel("Africa/Conakry") },
  { value: "Africa/Dakar", label: toLabel("Africa/Dakar") },
  { value: "Africa/Dar_es_Salaam", label: toLabel("Africa/Dar_es_Salaam") },
  { value: "Africa/Djibouti", label: toLabel("Africa/Djibouti") },
  { value: "Africa/Douala", label: toLabel("Africa/Douala") },
  { value: "Africa/El_Aaiun", label: toLabel("Africa/El_Aaiun") },
  { value: "Africa/Freetown", label: toLabel("Africa/Freetown") },
  { value: "Africa/Gaborone", label: toLabel("Africa/Gaborone") },
  { value: "Africa/Harare", label: toLabel("Africa/Harare") },
  { value: "Africa/Johannesburg", label: toLabel("Africa/Johannesburg") },
  { value: "Africa/Juba", label: toLabel("Africa/Juba") },
  { value: "Africa/Kampala", label: toLabel("Africa/Kampala") },
  { value: "Africa/Khartoum", label: toLabel("Africa/Khartoum") },
  { value: "Africa/Kigali", label: toLabel("Africa/Kigali") },
  { value: "Africa/Kinshasa", label: toLabel("Africa/Kinshasa") },
  { value: "Africa/Lagos", label: toLabel("Africa/Lagos") },
  { value: "Africa/Libreville", label: toLabel("Africa/Libreville") },
  { value: "Africa/Lome", label: toLabel("Africa/Lome") },
  { value: "Africa/Luanda", label: toLabel("Africa/Luanda") },
  { value: "Africa/Lubumbashi", label: toLabel("Africa/Lubumbashi") },
  { value: "Africa/Lusaka", label: toLabel("Africa/Lusaka") },
  { value: "Africa/Malabo", label: toLabel("Africa/Malabo") },
  { value: "Africa/Maputo", label: toLabel("Africa/Maputo") },
  { value: "Africa/Maseru", label: toLabel("Africa/Maseru") },
  { value: "Africa/Mbabane", label: toLabel("Africa/Mbabane") },
  { value: "Africa/Mogadishu", label: toLabel("Africa/Mogadishu") },
  { value: "Africa/Monrovia", label: toLabel("Africa/Monrovia") },
  { value: "Africa/Nairobi", label: toLabel("Africa/Nairobi") },
  { value: "Africa/Ndjamena", label: toLabel("Africa/Ndjamena") },
  { value: "Africa/Niamey", label: toLabel("Africa/Niamey") },
  { value: "Africa/Nouakchott", label: toLabel("Africa/Nouakchott") },
  { value: "Africa/Ouagadougou", label: toLabel("Africa/Ouagadougou") },
  { value: "Africa/Porto-Novo", label: toLabel("Africa/Porto-Novo") },
  { value: "Africa/Sao_Tome", label: toLabel("Africa/Sao_Tome") },
  { value: "Africa/Tripoli", label: toLabel("Africa/Tripoli") },
  { value: "Africa/Tunis", label: toLabel("Africa/Tunis") },
  { value: "Africa/Windhoek", label: toLabel("Africa/Windhoek") },
  { value: "America/Adak", label: toLabel("America/Adak") },
  { value: "America/Anchorage", label: toLabel("America/Anchorage") },
  { value: "America/Anguilla", label: toLabel("America/Anguilla") },
  { value: "America/Antigua", label: toLabel("America/Antigua") },
  { value: "America/Araguaina", label: toLabel("America/Araguaina") },
  { value: "America/Argentina/La_Rioja", label: toLabel("America/Argentina/La_Rioja") },
  { value: "America/Argentina/Rio_Gallegos", label: toLabel("America/Argentina/Rio_Gallegos") },
  { value: "America/Argentina/Salta", label: toLabel("America/Argentina/Salta") },
  { value: "America/Argentina/San_Juan", label: toLabel("America/Argentina/San_Juan") },
  { value: "America/Argentina/San_Luis", label: toLabel("America/Argentina/San_Luis") },
  { value: "America/Argentina/Tucuman", label: toLabel("America/Argentina/Tucuman") },
  { value: "America/Argentina/Ushuaia", label: toLabel("America/Argentina/Ushuaia") },
  { value: "America/Aruba", label: toLabel("America/Aruba") },
  { value: "America/Asuncion", label: toLabel("America/Asuncion") },
  { value: "America/Bahia", label: toLabel("America/Bahia") },
  { value: "America/Bahia_Banderas", label: toLabel("America/Bahia_Banderas") },
  { value: "America/Barbados", label: toLabel("America/Barbados") },
  { value: "America/Belem", label: toLabel("America/Belem") },
  { value: "America/Belize", label: toLabel("America/Belize") },
  { value: "America/Blanc-Sablon", label: toLabel("America/Blanc-Sablon") },
  { value: "America/Boa_Vista", label: toLabel("America/Boa_Vista") },
  { value: "America/Bogota", label: toLabel("America/Bogota") },
  { value: "America/Boise", label: toLabel("America/Boise") },
  { value: "America/Buenos_Aires", label: toLabel("America/Buenos_Aires") },
  { value: "America/Cambridge_Bay", label: toLabel("America/Cambridge_Bay") },
  { value: "America/Campo_Grande", label: toLabel("America/Campo_Grande") },
  { value: "America/Cancun", label: toLabel("America/Cancun") },
  { value: "America/Caracas", label: toLabel("America/Caracas") },
  { value: "America/Catamarca", label: toLabel("America/Catamarca") },
  { value: "America/Cayenne", label: toLabel("America/Cayenne") },
  { value: "America/Cayman", label: toLabel("America/Cayman") },
  { value: "America/Chicago", label: toLabel("America/Chicago") },
  { value: "America/Chihuahua", label: toLabel("America/Chihuahua") },
  { value: "America/Ciudad_Juarez", label: toLabel("America/Ciudad_Juarez") },
  { value: "America/Coral_Harbour", label: toLabel("America/Coral_Harbour") },
  { value: "America/Cordoba", label: toLabel("America/Cordoba") },
  { value: "America/Costa_Rica", label: toLabel("America/Costa_Rica") },
  { value: "America/Coyhaique", label: toLabel("America/Coyhaique") },
  { value: "America/Creston", label: toLabel("America/Creston") },
  { value: "America/Cuiaba", label: toLabel("America/Cuiaba") },
  { value: "America/Curacao", label: toLabel("America/Curacao") },
  { value: "America/Danmarkshavn", label: toLabel("America/Danmarkshavn") },
  { value: "America/Dawson", label: toLabel("America/Dawson") },
  { value: "America/Dawson_Creek", label: toLabel("America/Dawson_Creek") },
  { value: "America/Denver", label: toLabel("America/Denver") },
  { value: "America/Detroit", label: toLabel("America/Detroit") },
  { value: "America/Dominica", label: toLabel("America/Dominica") },
  { value: "America/Edmonton", label: toLabel("America/Edmonton") },
  { value: "America/Eirunepe", label: toLabel("America/Eirunepe") },
  { value: "America/El_Salvador", label: toLabel("America/El_Salvador") },
  { value: "America/Fort_Nelson", label: toLabel("America/Fort_Nelson") },
  { value: "America/Fortaleza", label: toLabel("America/Fortaleza") },
  { value: "America/Glace_Bay", label: toLabel("America/Glace_Bay") },
  { value: "America/Godthab", label: toLabel("America/Godthab") },
  { value: "America/Goose_Bay", label: toLabel("America/Goose_Bay") },
  { value: "America/Grand_Turk", label: toLabel("America/Grand_Turk") },
  { value: "America/Grenada", label: toLabel("America/Grenada") },
  { value: "America/Guadeloupe", label: toLabel("America/Guadeloupe") },
  { value: "America/Guatemala", label: toLabel("America/Guatemala") },
  { value: "America/Guayaquil", label: toLabel("America/Guayaquil") },
  { value: "America/Guyana", label: toLabel("America/Guyana") },
  { value: "America/Halifax", label: toLabel("America/Halifax") },
  { value: "America/Havana", label: toLabel("America/Havana") },
  { value: "America/Hermosillo", label: toLabel("America/Hermosillo") },
  { value: "America/Indiana/Knox", label: toLabel("America/Indiana/Knox") },
  { value: "America/Indiana/Marengo", label: toLabel("America/Indiana/Marengo") },
  { value: "America/Indiana/Petersburg", label: toLabel("America/Indiana/Petersburg") },
  { value: "America/Indiana/Tell_City", label: toLabel("America/Indiana/Tell_City") },
  { value: "America/Indiana/Vevay", label: toLabel("America/Indiana/Vevay") },
  { value: "America/Indiana/Vincennes", label: toLabel("America/Indiana/Vincennes") },
  { value: "America/Indiana/Winamac", label: toLabel("America/Indiana/Winamac") },
  { value: "America/Indianapolis", label: toLabel("America/Indianapolis") },
  { value: "America/Inuvik", label: toLabel("America/Inuvik") },
  { value: "America/Iqaluit", label: toLabel("America/Iqaluit") },
  { value: "America/Jamaica", label: toLabel("America/Jamaica") },
  { value: "America/Jujuy", label: toLabel("America/Jujuy") },
  { value: "America/Juneau", label: toLabel("America/Juneau") },
  { value: "America/Kentucky/Monticello", label: toLabel("America/Kentucky/Monticello") },
  { value: "America/Kralendijk", label: toLabel("America/Kralendijk") },
  { value: "America/La_Paz", label: toLabel("America/La_Paz") },
  { value: "America/Lima", label: toLabel("America/Lima") },
  { value: "America/Los_Angeles", label: toLabel("America/Los_Angeles") },
  { value: "America/Louisville", label: toLabel("America/Louisville") },
  { value: "America/Lower_Princes", label: toLabel("America/Lower_Princes") },
  { value: "America/Maceio", label: toLabel("America/Maceio") },
  { value: "America/Managua", label: toLabel("America/Managua") },
  { value: "America/Manaus", label: toLabel("America/Manaus") },
  { value: "America/Marigot", label: toLabel("America/Marigot") },
  { value: "America/Martinique", label: toLabel("America/Martinique") },
  { value: "America/Matamoros", label: toLabel("America/Matamoros") },
  { value: "America/Mazatlan", label: toLabel("America/Mazatlan") },
  { value: "America/Mendoza", label: toLabel("America/Mendoza") },
  { value: "America/Menominee", label: toLabel("America/Menominee") },
  { value: "America/Merida", label: toLabel("America/Merida") },
  { value: "America/Metlakatla", label: toLabel("America/Metlakatla") },
  { value: "America/Mexico_City", label: toLabel("America/Mexico_City") },
  { value: "America/Miquelon", label: toLabel("America/Miquelon") },
  { value: "America/Moncton", label: toLabel("America/Moncton") },
  { value: "America/Monterrey", label: toLabel("America/Monterrey") },
  { value: "America/Montevideo", label: toLabel("America/Montevideo") },
  { value: "America/Montserrat", label: toLabel("America/Montserrat") },
  { value: "America/Nassau", label: toLabel("America/Nassau") },
  { value: "America/New_York", label: toLabel("America/New_York") },
  { value: "America/Nome", label: toLabel("America/Nome") },
  { value: "America/Noronha", label: toLabel("America/Noronha") },
  { value: "America/North_Dakota/Beulah", label: toLabel("America/North_Dakota/Beulah") },
  { value: "America/North_Dakota/Center", label: toLabel("America/North_Dakota/Center") },
  { value: "America/North_Dakota/New_Salem", label: toLabel("America/North_Dakota/New_Salem") },
  { value: "America/Ojinaga", label: toLabel("America/Ojinaga") },
  { value: "America/Panama", label: toLabel("America/Panama") },
  { value: "America/Paramaribo", label: toLabel("America/Paramaribo") },
  { value: "America/Phoenix", label: toLabel("America/Phoenix") },
  { value: "America/Port-au-Prince", label: toLabel("America/Port-au-Prince") },
  { value: "America/Port_of_Spain", label: toLabel("America/Port_of_Spain") },
  { value: "America/Porto_Velho", label: toLabel("America/Porto_Velho") },
  { value: "America/Puerto_Rico", label: toLabel("America/Puerto_Rico") },
  { value: "America/Punta_Arenas", label: toLabel("America/Punta_Arenas") },
  { value: "America/Rankin_Inlet", label: toLabel("America/Rankin_Inlet") },
  { value: "America/Recife", label: toLabel("America/Recife") },
  { value: "America/Regina", label: toLabel("America/Regina") },
  { value: "America/Resolute", label: toLabel("America/Resolute") },
  { value: "America/Rio_Branco", label: toLabel("America/Rio_Branco") },
  { value: "America/Santarem", label: toLabel("America/Santarem") },
  { value: "America/Santiago", label: toLabel("America/Santiago") },
  { value: "America/Santo_Domingo", label: toLabel("America/Santo_Domingo") },
  { value: "America/Sao_Paulo", label: toLabel("America/Sao_Paulo") },
  { value: "America/Scoresbysund", label: toLabel("America/Scoresbysund") },
  { value: "America/Sitka", label: toLabel("America/Sitka") },
  { value: "America/St_Barthelemy", label: toLabel("America/St_Barthelemy") },
  { value: "America/St_Johns", label: toLabel("America/St_Johns") },
  { value: "America/St_Kitts", label: toLabel("America/St_Kitts") },
  { value: "America/St_Lucia", label: toLabel("America/St_Lucia") },
  { value: "America/St_Thomas", label: toLabel("America/St_Thomas") },
  { value: "America/St_Vincent", label: toLabel("America/St_Vincent") },
  { value: "America/Swift_Current", label: toLabel("America/Swift_Current") },
  { value: "America/Tegucigalpa", label: toLabel("America/Tegucigalpa") },
  { value: "America/Thule", label: toLabel("America/Thule") },
  { value: "America/Tijuana", label: toLabel("America/Tijuana") },
  { value: "America/Toronto", label: toLabel("America/Toronto") },
  { value: "America/Tortola", label: toLabel("America/Tortola") },
  { value: "America/Vancouver", label: toLabel("America/Vancouver") },
  { value: "America/Whitehorse", label: toLabel("America/Whitehorse") },
  { value: "America/Winnipeg", label: toLabel("America/Winnipeg") },
  { value: "America/Yakutat", label: toLabel("America/Yakutat") },
  { value: "Antarctica/Casey", label: toLabel("Antarctica/Casey") },
  { value: "Antarctica/Davis", label: toLabel("Antarctica/Davis") },
  { value: "Antarctica/DumontDUrville", label: toLabel("Antarctica/DumontDUrville") },
  { value: "Antarctica/Macquarie", label: toLabel("Antarctica/Macquarie") },
  { value: "Antarctica/Mawson", label: toLabel("Antarctica/Mawson") },
  { value: "Antarctica/McMurdo", label: toLabel("Antarctica/McMurdo") },
  { value: "Antarctica/Palmer", label: toLabel("Antarctica/Palmer") },
  { value: "Antarctica/Rothera", label: toLabel("Antarctica/Rothera") },
  { value: "Antarctica/Syowa", label: toLabel("Antarctica/Syowa") },
  { value: "Antarctica/Troll", label: toLabel("Antarctica/Troll") },
  { value: "Antarctica/Vostok", label: toLabel("Antarctica/Vostok") },
  { value: "Arctic/Longyearbyen", label: toLabel("Arctic/Longyearbyen") },
  { value: "Asia/Aden", label: toLabel("Asia/Aden") },
  { value: "Asia/Almaty", label: toLabel("Asia/Almaty") },
  { value: "Asia/Amman", label: toLabel("Asia/Amman") },
  { value: "Asia/Anadyr", label: toLabel("Asia/Anadyr") },
  { value: "Asia/Aqtau", label: toLabel("Asia/Aqtau") },
  { value: "Asia/Aqtobe", label: toLabel("Asia/Aqtobe") },
  { value: "Asia/Ashgabat", label: toLabel("Asia/Ashgabat") },
  { value: "Asia/Atyrau", label: toLabel("Asia/Atyrau") },
  { value: "Asia/Baghdad", label: toLabel("Asia/Baghdad") },
  { value: "Asia/Bahrain", label: toLabel("Asia/Bahrain") },
  { value: "Asia/Baku", label: toLabel("Asia/Baku") },
  { value: "Asia/Bangkok", label: toLabel("Asia/Bangkok") },
  { value: "Asia/Barnaul", label: toLabel("Asia/Barnaul") },
  { value: "Asia/Beirut", label: toLabel("Asia/Beirut") },
  { value: "Asia/Bishkek", label: toLabel("Asia/Bishkek") },
  { value: "Asia/Brunei", label: toLabel("Asia/Brunei") },
  { value: "Asia/Calcutta", label: toLabel("Asia/Calcutta") },
  { value: "Asia/Chita", label: toLabel("Asia/Chita") },
  { value: "Asia/Colombo", label: toLabel("Asia/Colombo") },
  { value: "Asia/Damascus", label: toLabel("Asia/Damascus") },
  { value: "Asia/Dhaka", label: toLabel("Asia/Dhaka") },
  { value: "Asia/Dili", label: toLabel("Asia/Dili") },
  { value: "Asia/Dubai", label: toLabel("Asia/Dubai") },
  { value: "Asia/Dushanbe", label: toLabel("Asia/Dushanbe") },
  { value: "Asia/Famagusta", label: toLabel("Asia/Famagusta") },
  { value: "Asia/Gaza", label: toLabel("Asia/Gaza") },
  { value: "Asia/Hebron", label: toLabel("Asia/Hebron") },
  { value: "Asia/Hong_Kong", label: toLabel("Asia/Hong_Kong") },
  { value: "Asia/Hovd", label: toLabel("Asia/Hovd") },
  { value: "Asia/Irkutsk", label: toLabel("Asia/Irkutsk") },
  { value: "Asia/Jakarta", label: toLabel("Asia/Jakarta") },
  { value: "Asia/Jayapura", label: toLabel("Asia/Jayapura") },
  { value: "Asia/Jerusalem", label: toLabel("Asia/Jerusalem") },
  { value: "Asia/Kabul", label: toLabel("Asia/Kabul") },
  { value: "Asia/Kamchatka", label: toLabel("Asia/Kamchatka") },
  { value: "Asia/Karachi", label: toLabel("Asia/Karachi") },
  { value: "Asia/Katmandu", label: toLabel("Asia/Katmandu") },
  { value: "Asia/Khandyga", label: toLabel("Asia/Khandyga") },
  { value: "Asia/Krasnoyarsk", label: toLabel("Asia/Krasnoyarsk") },
  { value: "Asia/Kuala_Lumpur", label: toLabel("Asia/Kuala_Lumpur") },
  { value: "Asia/Kuching", label: toLabel("Asia/Kuching") },
  { value: "Asia/Kuwait", label: toLabel("Asia/Kuwait") },
  { value: "Asia/Macau", label: toLabel("Asia/Macau") },
  { value: "Asia/Magadan", label: toLabel("Asia/Magadan") },
  { value: "Asia/Makassar", label: toLabel("Asia/Makassar") },
  { value: "Asia/Manila", label: toLabel("Asia/Manila") },
  { value: "Asia/Muscat", label: toLabel("Asia/Muscat") },
  { value: "Asia/Nicosia", label: toLabel("Asia/Nicosia") },
  { value: "Asia/Novokuznetsk", label: toLabel("Asia/Novokuznetsk") },
  { value: "Asia/Novosibirsk", label: toLabel("Asia/Novosibirsk") },
  { value: "Asia/Omsk", label: toLabel("Asia/Omsk") },
  { value: "Asia/Oral", label: toLabel("Asia/Oral") },
  { value: "Asia/Phnom_Penh", label: toLabel("Asia/Phnom_Penh") },
  { value: "Asia/Pontianak", label: toLabel("Asia/Pontianak") },
  { value: "Asia/Pyongyang", label: toLabel("Asia/Pyongyang") },
  { value: "Asia/Qatar", label: toLabel("Asia/Qatar") },
  { value: "Asia/Qostanay", label: toLabel("Asia/Qostanay") },
  { value: "Asia/Qyzylorda", label: toLabel("Asia/Qyzylorda") },
  { value: "Asia/Rangoon", label: toLabel("Asia/Rangoon") },
  { value: "Asia/Riyadh", label: toLabel("Asia/Riyadh") },
  { value: "Asia/Saigon", label: toLabel("Asia/Saigon") },
  { value: "Asia/Sakhalin", label: toLabel("Asia/Sakhalin") },
  { value: "Asia/Samarkand", label: toLabel("Asia/Samarkand") },
  { value: "Asia/Seoul", label: toLabel("Asia/Seoul") },
  { value: "Asia/Shanghai", label: toLabel("Asia/Shanghai") },
  { value: "Asia/Singapore", label: toLabel("Asia/Singapore") },
  { value: "Asia/Srednekolymsk", label: toLabel("Asia/Srednekolymsk") },
  { value: "Asia/Taipei", label: toLabel("Asia/Taipei") },
  { value: "Asia/Tashkent", label: toLabel("Asia/Tashkent") },
  { value: "Asia/Tbilisi", label: toLabel("Asia/Tbilisi") },
  { value: "Asia/Tehran", label: toLabel("Asia/Tehran") },
  { value: "Asia/Thimphu", label: toLabel("Asia/Thimphu") },
  { value: "Asia/Tokyo", label: toLabel("Asia/Tokyo") },
  { value: "Asia/Tomsk", label: toLabel("Asia/Tomsk") },
  { value: "Asia/Ulaanbaatar", label: toLabel("Asia/Ulaanbaatar") },
  { value: "Asia/Urumqi", label: toLabel("Asia/Urumqi") },
  { value: "Asia/Ust-Nera", label: toLabel("Asia/Ust-Nera") },
  { value: "Asia/Vientiane", label: toLabel("Asia/Vientiane") },
  { value: "Asia/Vladivostok", label: toLabel("Asia/Vladivostok") },
  { value: "Asia/Yakutsk", label: toLabel("Asia/Yakutsk") },
  { value: "Asia/Yekaterinburg", label: toLabel("Asia/Yekaterinburg") },
  { value: "Asia/Yerevan", label: toLabel("Asia/Yerevan") },
  { value: "Atlantic/Azores", label: toLabel("Atlantic/Azores") },
  { value: "Atlantic/Bermuda", label: toLabel("Atlantic/Bermuda") },
  { value: "Atlantic/Canary", label: toLabel("Atlantic/Canary") },
  { value: "Atlantic/Cape_Verde", label: toLabel("Atlantic/Cape_Verde") },
  { value: "Atlantic/Faeroe", label: toLabel("Atlantic/Faeroe") },
  { value: "Atlantic/Madeira", label: toLabel("Atlantic/Madeira") },
  { value: "Atlantic/Reykjavik", label: toLabel("Atlantic/Reykjavik") },
  { value: "Atlantic/South_Georgia", label: toLabel("Atlantic/South_Georgia") },
  { value: "Atlantic/St_Helena", label: toLabel("Atlantic/St_Helena") },
  { value: "Atlantic/Stanley", label: toLabel("Atlantic/Stanley") },
  { value: "Australia/Adelaide", label: toLabel("Australia/Adelaide") },
  { value: "Australia/Brisbane", label: toLabel("Australia/Brisbane") },
  { value: "Australia/Broken_Hill", label: toLabel("Australia/Broken_Hill") },
  { value: "Australia/Darwin", label: toLabel("Australia/Darwin") },
  { value: "Australia/Eucla", label: toLabel("Australia/Eucla") },
  { value: "Australia/Hobart", label: toLabel("Australia/Hobart") },
  { value: "Australia/Lindeman", label: toLabel("Australia/Lindeman") },
  { value: "Australia/Lord_Howe", label: toLabel("Australia/Lord_Howe") },
  { value: "Australia/Melbourne", label: toLabel("Australia/Melbourne") },
  { value: "Australia/Perth", label: toLabel("Australia/Perth") },
  { value: "Australia/Sydney", label: toLabel("Australia/Sydney") },
  { value: "Europe/Amsterdam", label: toLabel("Europe/Amsterdam") },
  { value: "Europe/Andorra", label: toLabel("Europe/Andorra") },
  { value: "Europe/Astrakhan", label: toLabel("Europe/Astrakhan") },
  { value: "Europe/Athens", label: toLabel("Europe/Athens") },
  { value: "Europe/Belgrade", label: toLabel("Europe/Belgrade") },
  { value: "Europe/Berlin", label: toLabel("Europe/Berlin") },
  { value: "Europe/Bratislava", label: toLabel("Europe/Bratislava") },
  { value: "Europe/Brussels", label: toLabel("Europe/Brussels") },
  { value: "Europe/Bucharest", label: toLabel("Europe/Bucharest") },
  { value: "Europe/Budapest", label: toLabel("Europe/Budapest") },
  { value: "Europe/Busingen", label: toLabel("Europe/Busingen") },
  { value: "Europe/Chisinau", label: toLabel("Europe/Chisinau") },
  { value: "Europe/Copenhagen", label: toLabel("Europe/Copenhagen") },
  { value: "Europe/Dublin", label: toLabel("Europe/Dublin") },
  { value: "Europe/Gibraltar", label: toLabel("Europe/Gibraltar") },
  { value: "Europe/Guernsey", label: toLabel("Europe/Guernsey") },
  { value: "Europe/Helsinki", label: toLabel("Europe/Helsinki") },
  { value: "Europe/Isle_of_Man", label: toLabel("Europe/Isle_of_Man") },
  { value: "Europe/Istanbul", label: toLabel("Europe/Istanbul") },
  { value: "Europe/Jersey", label: toLabel("Europe/Jersey") },
  { value: "Europe/Kaliningrad", label: toLabel("Europe/Kaliningrad") },
  { value: "Europe/Kiev", label: toLabel("Europe/Kiev") },
  { value: "Europe/Kirov", label: toLabel("Europe/Kirov") },
  { value: "Europe/Lisbon", label: toLabel("Europe/Lisbon") },
  { value: "Europe/Ljubljana", label: toLabel("Europe/Ljubljana") },
  { value: "Europe/London", label: toLabel("Europe/London") },
  { value: "Europe/Luxembourg", label: toLabel("Europe/Luxembourg") },
  { value: "Europe/Madrid", label: toLabel("Europe/Madrid") },
  { value: "Europe/Malta", label: toLabel("Europe/Malta") },
  { value: "Europe/Mariehamn", label: toLabel("Europe/Mariehamn") },
  { value: "Europe/Minsk", label: toLabel("Europe/Minsk") },
  { value: "Europe/Monaco", label: toLabel("Europe/Monaco") },
  { value: "Europe/Moscow", label: toLabel("Europe/Moscow") },
  { value: "Europe/Oslo", label: toLabel("Europe/Oslo") },
  { value: "Europe/Paris", label: toLabel("Europe/Paris") },
  { value: "Europe/Podgorica", label: toLabel("Europe/Podgorica") },
  { value: "Europe/Prague", label: toLabel("Europe/Prague") },
  { value: "Europe/Riga", label: toLabel("Europe/Riga") },
  { value: "Europe/Rome", label: toLabel("Europe/Rome") },
  { value: "Europe/Samara", label: toLabel("Europe/Samara") },
  { value: "Europe/San_Marino", label: toLabel("Europe/San_Marino") },
  { value: "Europe/Sarajevo", label: toLabel("Europe/Sarajevo") },
  { value: "Europe/Saratov", label: toLabel("Europe/Saratov") },
  { value: "Europe/Simferopol", label: toLabel("Europe/Simferopol") },
  { value: "Europe/Skopje", label: toLabel("Europe/Skopje") },
  { value: "Europe/Sofia", label: toLabel("Europe/Sofia") },
  { value: "Europe/Stockholm", label: toLabel("Europe/Stockholm") },
  { value: "Europe/Tallinn", label: toLabel("Europe/Tallinn") },
  { value: "Europe/Tirane", label: toLabel("Europe/Tirane") },
  { value: "Europe/Ulyanovsk", label: toLabel("Europe/Ulyanovsk") },
  { value: "Europe/Vaduz", label: toLabel("Europe/Vaduz") },
  { value: "Europe/Vatican", label: toLabel("Europe/Vatican") },
  { value: "Europe/Vienna", label: toLabel("Europe/Vienna") },
  { value: "Europe/Vilnius", label: toLabel("Europe/Vilnius") },
  { value: "Europe/Volgograd", label: toLabel("Europe/Volgograd") },
  { value: "Europe/Warsaw", label: toLabel("Europe/Warsaw") },
  { value: "Europe/Zagreb", label: toLabel("Europe/Zagreb") },
  { value: "Europe/Zurich", label: toLabel("Europe/Zurich") },
  { value: "Indian/Antananarivo", label: toLabel("Indian/Antananarivo") },
  { value: "Indian/Chagos", label: toLabel("Indian/Chagos") },
  { value: "Indian/Christmas", label: toLabel("Indian/Christmas") },
  { value: "Indian/Cocos", label: toLabel("Indian/Cocos") },
  { value: "Indian/Comoro", label: toLabel("Indian/Comoro") },
  { value: "Indian/Kerguelen", label: toLabel("Indian/Kerguelen") },
  { value: "Indian/Mahe", label: toLabel("Indian/Mahe") },
  { value: "Indian/Maldives", label: toLabel("Indian/Maldives") },
  { value: "Indian/Mauritius", label: toLabel("Indian/Mauritius") },
  { value: "Indian/Mayotte", label: toLabel("Indian/Mayotte") },
  { value: "Indian/Reunion", label: toLabel("Indian/Reunion") },
  { value: "Pacific/Apia", label: toLabel("Pacific/Apia") },
  { value: "Pacific/Auckland", label: toLabel("Pacific/Auckland") },
  { value: "Pacific/Bougainville", label: toLabel("Pacific/Bougainville") },
  { value: "Pacific/Chatham", label: toLabel("Pacific/Chatham") },
  { value: "Pacific/Easter", label: toLabel("Pacific/Easter") },
  { value: "Pacific/Efate", label: toLabel("Pacific/Efate") },
  { value: "Pacific/Enderbury", label: toLabel("Pacific/Enderbury") },
  { value: "Pacific/Fakaofo", label: toLabel("Pacific/Fakaofo") },
  { value: "Pacific/Fiji", label: toLabel("Pacific/Fiji") },
  { value: "Pacific/Funafuti", label: toLabel("Pacific/Funafuti") },
  { value: "Pacific/Galapagos", label: toLabel("Pacific/Galapagos") },
  { value: "Pacific/Gambier", label: toLabel("Pacific/Gambier") },
  { value: "Pacific/Guadalcanal", label: toLabel("Pacific/Guadalcanal") },
  { value: "Pacific/Guam", label: toLabel("Pacific/Guam") },
  { value: "Pacific/Honolulu", label: toLabel("Pacific/Honolulu") },
  { value: "Pacific/Kiritimati", label: toLabel("Pacific/Kiritimati") },
  { value: "Pacific/Kosrae", label: toLabel("Pacific/Kosrae") },
  { value: "Pacific/Kwajalein", label: toLabel("Pacific/Kwajalein") },
  { value: "Pacific/Majuro", label: toLabel("Pacific/Majuro") },
  { value: "Pacific/Marquesas", label: toLabel("Pacific/Marquesas") },
  { value: "Pacific/Midway", label: toLabel("Pacific/Midway") },
  { value: "Pacific/Nauru", label: toLabel("Pacific/Nauru") },
  { value: "Pacific/Niue", label: toLabel("Pacific/Niue") },
  { value: "Pacific/Norfolk", label: toLabel("Pacific/Norfolk") },
  { value: "Pacific/Noumea", label: toLabel("Pacific/Noumea") },
  { value: "Pacific/Pago_Pago", label: toLabel("Pacific/Pago_Pago") },
  { value: "Pacific/Palau", label: toLabel("Pacific/Palau") },
  { value: "Pacific/Pitcairn", label: toLabel("Pacific/Pitcairn") },
  { value: "Pacific/Ponape", label: toLabel("Pacific/Ponape") },
  { value: "Pacific/Port_Moresby", label: toLabel("Pacific/Port_Moresby") },
  { value: "Pacific/Rarotonga", label: toLabel("Pacific/Rarotonga") },
  { value: "Pacific/Saipan", label: toLabel("Pacific/Saipan") },
  { value: "Pacific/Tahiti", label: toLabel("Pacific/Tahiti") },
  { value: "Pacific/Tarawa", label: toLabel("Pacific/Tarawa") },
  { value: "Pacific/Tongatapu", label: toLabel("Pacific/Tongatapu") },
  { value: "Pacific/Truk", label: toLabel("Pacific/Truk") },
  { value: "Pacific/Wake", label: toLabel("Pacific/Wake") },
  { value: "Pacific/Wallis", label: toLabel("Pacific/Wallis") },
];

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { value: "Etc/GMT+12", label: "International Date Line West" },
  { value: "Etc/GMT+11", label: "Coordinated Universal Time-11" },
  { value: "America/Adak", label: "Aleutian Islands" },
  { value: "Pacific/Honolulu", label: "Hawaii" },
  { value: "Pacific/Marquesas", label: "Marquesas Islands" },
  { value: "America/Anchorage", label: "Alaska" },
  { value: "Etc/GMT+9", label: "Coordinated Universal Time-09" },
  { value: "America/Tijuana", label: "Baja California" },
  { value: "Etc/GMT+8", label: "Coordinated Universal Time-08" },
  { value: "America/Los_Angeles", label: "Pacific Time (US & Canada)" },
  { value: "America/Phoenix", label: "Arizona" },
  { value: "America/Mazatlan", label: "La Paz, Mazatlan" },
  { value: "America/Denver", label: "Mountain Time (US & Canada)" },
  { value: "America/Whitehorse", label: "Yukon" },
  { value: "America/Guatemala", label: "Central America" },
  { value: "America/Chicago", label: "Central Time (US & Canada)" },
  { value: "Pacific/Easter", label: "Easter Island" },
  { value: "America/Mexico_City", label: "Guadalajara, Mexico City, Monterrey" },
  { value: "America/Regina", label: "Saskatchewan" },
  { value: "America/Bogota", label: "Bogota, Lima, Quito, Rio Branco" },
  { value: "America/Cancun", label: "Chetumal" },
  { value: "America/New_York", label: "Eastern Time (US & Canada)" },
  { value: "America/Port-au-Prince", label: "Haiti" },
  { value: "America/Havana", label: "Havana" },
  { value: "America/Indianapolis", label: "Indiana (East)" },
  { value: "America/Grand_Turk", label: "Turks and Caicos" },
  { value: "America/Halifax", label: "Atlantic Time (Canada)" },
  { value: "America/Caracas", label: "Caracas" },
  { value: "America/Cuiaba", label: "Cuiaba" },
  { value: "America/La_Paz", label: "Georgetown, La Paz, Manaus, San Juan" },
  { value: "America/Santiago", label: "Santiago" },
  { value: "America/St_Johns", label: "Newfoundland" },
  { value: "America/Araguaina", label: "Araguaina" },
  { value: "America/Asuncion", label: "Asuncion" },
  { value: "America/Sao_Paulo", label: "Brasilia" },
  { value: "America/Cayenne", label: "Cayenne, Fortaleza" },
  { value: "America/Buenos_Aires", label: "City of Buenos Aires" },
  { value: "America/Montevideo", label: "Montevideo" },
  { value: "America/Punta_Arenas", label: "Punta Arenas" },
  { value: "America/Miquelon", label: "Saint Pierre and Miquelon" },
  { value: "America/Bahia", label: "Salvador" },
  { value: "Etc/GMT+2", label: "Coordinated Universal Time-02" },
  { value: "America/Godthab", label: "Greenland" },
  { value: "Atlantic/Azores", label: "Azores" },
  { value: "Atlantic/Cape_Verde", label: "Cabo Verde Is." },
  { value: "Etc/UTC", label: "Coordinated Universal Time" },
  { value: "Europe/London", label: "Dublin, Edinburgh, Lisbon, London" },
  { value: "Atlantic/Reykjavik", label: "Monrovia, Reykjavik" },
  { value: "Africa/Sao_Tome", label: "Sao Tome" },
  { value: "Africa/Casablanca", label: "Casablanca" },
  { value: "Europe/Berlin", label: "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
  { value: "Europe/Budapest", label: "Belgrade, Bratislava, Budapest, Ljubljana, Prague" },
  { value: "Europe/Paris", label: "Brussels, Copenhagen, Madrid, Paris" },
  { value: "Europe/Warsaw", label: "Sarajevo, Skopje, Warsaw, Zagreb" },
  { value: "Africa/Lagos", label: "West Central Africa" },
  { value: "Europe/Bucharest", label: "Athens, Bucharest" },
  { value: "Asia/Beirut", label: "Beirut" },
  { value: "Africa/Cairo", label: "Cairo" },
  { value: "Europe/Chisinau", label: "Chisinau" },
  { value: "Asia/Hebron", label: "Gaza, Hebron" },
  { value: "Africa/Johannesburg", label: "Harare, Pretoria" },
  { value: "Europe/Kiev", label: "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
  { value: "Asia/Jerusalem", label: "Jerusalem" },
  { value: "Africa/Juba", label: "Juba" },
  { value: "Europe/Kaliningrad", label: "Kaliningrad" },
  { value: "Africa/Khartoum", label: "Khartoum" },
  { value: "Africa/Tripoli", label: "Tripoli" },
  { value: "Africa/Windhoek", label: "Windhoek" },
  { value: "Asia/Amman", label: "Amman" },
  { value: "Asia/Baghdad", label: "Baghdad" },
  { value: "Asia/Damascus", label: "Damascus" },
  { value: "Europe/Istanbul", label: "Istanbul" },
  { value: "Asia/Riyadh", label: "Kuwait, Riyadh" },
  { value: "Europe/Minsk", label: "Minsk" },
  { value: "Europe/Moscow", label: "Moscow, St. Petersburg" },
  { value: "Africa/Nairobi", label: "Nairobi" },
  { value: "Europe/Volgograd", label: "Volgograd" },
  { value: "Asia/Tehran", label: "Tehran" },
  { value: "Asia/Dubai", label: "Abu Dhabi, Muscat" },
  { value: "Europe/Astrakhan", label: "Astrakhan, Ulyanovsk" },
  { value: "Asia/Baku", label: "Baku" },
  { value: "Europe/Samara", label: "Izhevsk, Samara" },
  { value: "Indian/Mauritius", label: "Port Louis" },
  { value: "Europe/Saratov", label: "Saratov" },
  { value: "Asia/Tbilisi", label: "Tbilisi" },
  { value: "Asia/Yerevan", label: "Yerevan" },
  { value: "Asia/Kabul", label: "Kabul" },
  { value: "Asia/Tashkent", label: "Ashgabat, Tashkent" },
  { value: "Asia/Qyzylorda", label: "Astana" },
  { value: "Asia/Yekaterinburg", label: "Ekaterinburg" },
  { value: "Asia/Karachi", label: "Islamabad, Karachi" },
  { value: "Asia/Calcutta", label: "Chennai, Kolkata, Mumbai, New Delhi" },
  { value: "Asia/Colombo", label: "Sri Jayawardenepura" },
  { value: "Asia/Katmandu", label: "Kathmandu" },
  { value: "Asia/Bishkek", label: "Bishkek" },
  { value: "Asia/Dhaka", label: "Dhaka" },
  { value: "Asia/Omsk", label: "Omsk" },
  { value: "Asia/Rangoon", label: "Yangon (Rangoon)" },
  { value: "Asia/Bangkok", label: "Bangkok, Hanoi, Jakarta" },
  { value: "Asia/Barnaul", label: "Barnaul, Gorno-Altaysk" },
  { value: "Asia/Hovd", label: "Hovd" },
  { value: "Asia/Krasnoyarsk", label: "Krasnoyarsk" },
  { value: "Asia/Novosibirsk", label: "Novosibirsk" },
  { value: "Asia/Tomsk", label: "Tomsk" },
  { value: "Asia/Shanghai", label: "Beijing, Chongqing, Hong Kong, Urumqi" },
  { value: "Asia/Irkutsk", label: "Irkutsk" },
  { value: "Asia/Singapore", label: "Kuala Lumpur, Singapore" },
  { value: "Australia/Perth", label: "Perth" },
  { value: "Asia/Taipei", label: "Taipei" },
  { value: "Asia/Ulaanbaatar", label: "Ulaanbaatar" },
  { value: "Australia/Eucla", label: "Eucla" },
  { value: "Asia/Chita", label: "Chita" },
  { value: "Asia/Tokyo", label: "Osaka, Sapporo, Tokyo" },
  { value: "Asia/Pyongyang", label: "Pyongyang" },
  { value: "Asia/Seoul", label: "Seoul" },
  { value: "Asia/Yakutsk", label: "Yakutsk" },
  { value: "Australia/Adelaide", label: "Adelaide" },
  { value: "Australia/Darwin", label: "Darwin" },
  { value: "Australia/Brisbane", label: "Brisbane" },
  { value: "Australia/Sydney", label: "Canberra, Melbourne, Sydney" },
  { value: "Pacific/Port_Moresby", label: "Guam, Port Moresby" },
  { value: "Australia/Hobart", label: "Hobart" },
  { value: "Asia/Vladivostok", label: "Vladivostok" },
  { value: "Australia/Lord_Howe", label: "Lord Howe Island" },
  { value: "Pacific/Bougainville", label: "Bougainville Island" },
  { value: "Asia/Srednekolymsk", label: "Chokurdakh" },
  { value: "Asia/Magadan", label: "Magadan" },
  { value: "Pacific/Norfolk", label: "Norfolk Island" },
  { value: "Asia/Sakhalin", label: "Sakhalin" },
  { value: "Pacific/Guadalcanal", label: "Solomon Is., New Caledonia" },
  { value: "Asia/Kamchatka", label: "Anadyr, Petropavlovsk-Kamchatsky" },
  { value: "Pacific/Auckland", label: "Auckland, Wellington" },
  { value: "Etc/GMT-12", label: "Coordinated Universal Time+12" },
  { value: "Pacific/Fiji", label: "Fiji" },
  { value: "Pacific/Chatham", label: "Chatham Islands" },
  { value: "Etc/GMT-13", label: "Coordinated Universal Time+13" },
  { value: "Pacific/Tongatapu", label: "Nuku'alofa" },
  { value: "Pacific/Apia", label: "Samoa" },
  { value: "Pacific/Kiritimati", label: "Kiritimati Island" },
];

export const getTimezoneLabel = (timezone?: string | null) => {
  if (!timezone) return "UTC";

  const matched = TIMEZONE_OPTIONS.find((option) => option.value === timezone);
  if (matched) return matched.label;

  const allMatched = ALL_TIMEZONE_OPTIONS.find((option) => option.value === timezone);
  if (allMatched) return allMatched.label;

  return toLabel(timezone);
};

export const getTimezoneOffsetLabel = (timezone?: string | null) => {
  const zone = timezone || "UTC";
  const dateTime = DateTime.now().setZone(zone);

  if (!dateTime.isValid) {
    return "UTC+00:00";
  }

  const offsetMinutes = dateTime.offset;
  const sign = offsetMinutes >= 0 ? "+" : "-";
  const absoluteMinutes = Math.abs(offsetMinutes);
  const hours = String(Math.floor(absoluteMinutes / 60)).padStart(2, "0");
  const minutes = String(absoluteMinutes % 60).padStart(2, "0");

  return `UTC${sign}${hours}:${minutes}`;
};
